### ISSUE TITLE
Compatibility with fontaine when using css variables

### ISSUE THREAD

**Issue by florian-lefebvre** [rishi-raj-jain/astro-font#11]
https://github.com/unjs/fontaine is a neat project around fonts. When using CSS Variables (at the end of https://github.com/unjs/fontaine#usage), it requires doing:
```diff
:root {
  /* ... */
-  --ifm-font-family-base: 'Poppins';
+  --ifm-font-family-base: 'Poppins', 'Poppins override';
```
So here is my request: when `cssVariable` is specificed, generate the following css variable: `--${cssVariable}: "${name}", "${name} override";` (pseudo-code, you get the idea)

**Comment by rishi-raj-jain** [comment]
So right now it'd emit:

```
--${cssVariable}: "${name}", "font_fallback_${randomString}, serif"
```

So if I get that correctly, you wanna be able to change the `font_fallback_${randomString}` to `${name} override` correct?

**Comment by rishi-raj-jain** [comment]
This is now possible per config's `fallbackName` property :)

**Comment by rishi-raj-jain** [comment]
README now illustrates the usage:

https://github.com/rishi-raj-jain/astro-font?tab=readme-ov-file#configuring-fallback-font-name

Example:

https://github.com/rishi-raj-jain/astro-font/blob/master/src/pages/second.astro#L15

Output:

https://github.com/rishi-raj-jain/astro-font/actions/runs/7569402648/job/20612611748#step:8:5
