### ISSUE TITLE
Fonts generated on every change

### ISSUE THREAD

**Issue by alexcarpenter** [rishi-raj-jain/astro-font#14]
Is there a way to reduce the console output. Not sure why these font files need generating on every change.

<img width="1582" alt="Screenshot 2024-01-19 at 7 01 59 AM" src="https://github.com/rishi-raj-jain/astro-font/assets/825855/5484f7c0-d2c1-41df-aa04-485ca45a35cb">

**Comment by rishi-raj-jain** [comment]
@alexcarpenter

I've just released another version of `astro-font` to take care of this.

Just in case you need to get the logs out, use the `verbose: true` flag as in https://github.com/rishi-raj-jain/astro-font/blob/master/src/pages/third.astro#L22

**Comment by alexcarpenter** [comment]
@rishi-raj-jain awesome, thank you!

**Comment by rishi-raj-jain** [comment]
> Not sure why these font files need generating on every change.

It's not font on every change but the cached fallback CSS of the generated fonts.
