### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by thatgurkangurk** [rishi-raj-jain/astro-font#16]
if you use `astro-font` on windows, the font is not loaded in the browser
<img src="https://github.com/rishi-raj-jain/astro-font/assets/82083756/d90a1816-04d3-4f92-88d3-fdc180914c24" alt="no font is displayed" width="500" />

there are also errors in the dev console
![image](https://github.com/rishi-raj-jain/astro-font/assets/82083756/0499314b-99a5-4f5b-81c6-db99de3caef9)

i could take a look at it and maybe make a pr if i have time, but i don't right now

code for the example: https://github.com/thatgurkangurk/gurkz.me

**Comment by rishi-raj-jain** [comment]
@thatgurkangurk

I've made a PR fixing the issue. Thanks for reporting!

**Comment by thatgurkangurk** [comment]
you're welcome
