### ISSUE TITLE
Feature request: add fallback for monospaced fonts

### ISSUE THREAD

**Issue by klasnasman** [rishi-raj-jain/astro-font#17]
Would be nice to also have a fallback for monospaced fonts

**Comment by jorgejhms** [comment]
Yeah, this should be a basic feature

**Comment by rishi-raj-jain** [comment]
Hey @klasnasman @jorgejhms,

Appreciate the interest on that! Certainly, I'm on it :D

**Comment by rishi-raj-jain** [comment]
Released in 0.0.78.

**Comment by rishi-raj-jain** [comment]
https://github.com/rishi-raj-jain/astro-font/releases/tag/78
