### ISSUE TITLE
Is style correctly defined in README?

### ISSUE THREAD

**Issue by 149203** [rishi-raj-jain/astro-font#19]
In https://github.com/rishi-raj-jain/astro-font/blob/master/packages/astro-font/README.md you are providing values like `style: 'bold'` and `style: 'medium'` when I believe the only acceptable values are `style: 'normal'` and `style: 'italic'` as per the Vercel docs: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#local-fonts

Please correct me if I am wrong.

**Comment by 149203** [comment]
I wrote this doc to help my team: [How to Use Astro-Font to Optimize Local Font Loading in Astro and Tailwind Projects](https://banneryear.notion.site/How-to-Use-Astro-Font-to-Optimize-Local-Font-Loading-in-Astro-and-Tailwind-Projects-d5ddc5f4e13e4182b81208f81a0c61ff)

**Comment by rishi-raj-jain** [comment]
Hey @149203,

- Let me get back to you on this particular issue in about 12 hours, have been pulling an all nighter for some other work today.

> I wrote this doc to help my team: [How to Use Astro-Font to Optimize Local Font Loading in Astro and Tailwind Projects](https://banneryear.notion.site/How-to-Use-Astro-Font-to-Optimize-Local-Font-Loading-in-Astro-and-Tailwind-Projects-d5ddc5f4e13e4182b81208f81a0c61ff)
- Woah, that's lovely really. I'll make sure to cross post it everywhere. Thank you so much! I am glad that I can contribute to the ecosystem and it's receiving such appreciation and usage.

- As I see it in https://www.channelkey.com/_astro/404.b639d0ea.css, CSS is being used to load fonts and are hashed through vite during the build. Using `astro-font` would definitely improve the DX a lot.

- I just sent out a LinkedIn connect request.

**Comment by rishi-raj-jain** [comment]
@149203 

You are correct. I've updated the `style` properties per the PR from @florian-lefebvre.

Thanks to you both that `astro-font` is improving.

**Comment by rishi-raj-jain** [comment]
> I wrote this doc to help my team: [How to Use Astro-Font to Optimize Local Font Loading in Astro and Tailwind Projects](https://banneryear.notion.site/How-to-Use-Astro-Font-to-Optimize-Local-Font-Loading-in-Astro-and-Tailwind-Projects-d5ddc5f4e13e4182b81208f81a0c61ff)

Shared this on my socials:

- https://twitter.com/rishi_raj_jain_/status/1776153693756252277
- https://peerlist.io/scroll/post/ACTH9OLG8RLJ88NDMC8OQJMB6QP86R
- https://www.linkedin.com/feed/update/urn:li:activity:7181919478501322752/
