### ISSUE TITLE
Node errors in Cloudlflare

### ISSUE THREAD

**Issue by shansmith01** [rishi-raj-jain/astro-font#20]
I am having an issue using astro-font with Cloudflare and I get the following errors at build time

11:04:08.553 | ✘ [ERROR] Could not resolve "node:path"
-- | --
11:04:08.554 |  
11:04:08.554 | _worker.js:108:22532:
11:04:08.554 | 108 │ ...w});import{join as j0}from"node:path";import{Buffer as uq}from...
11:04:08.554 | ╵                              ~~~~~~~~~~~
11:04:08.554 |  
11:04:08.554 | The package "node:path" wasn't found on the file system but is built into node.
11:04:08.555 | Add the "nodejs_compat" compatibility flag to your Pages project to enable Node.js compatibility.
11:04:08.555 |  
11:04:08.555 |  
11:04:08.555 | ✘ [ERROR] Could not resolve "node:buffer"
11:04:08.555 |  
11:04:08.555 | _worker.js:108:22568:
11:04:08.555 | 108 │ ...;import{Buffer as uq}from"node:buffer";function Wn(e,t,r,n){r=...
11:04:08.555 | ╵

I'm on "astro-font": "0.0.78",

I would love to get your plugin working. Thanks so much for your work

**Comment by rishi-raj-jain** [comment]
Hey @shansmith01,

Please enable nodejs_compat flag by CF Workers: https://developers.cloudflare.com/workers/runtime-apis/nodejs/#enable-nodejs-with-workers to support node imports.

I'm going to add this in the README.md as well.

Thank you for raising the issue!

**Comment by rishi-raj-jain** [comment]
I've updated the README.md as with below:

https://github.com/rishi-raj-jain/astro-font?tab=readme-ov-file#with-cloudflare-workers
