### ISSUE TITLE
No font's Loading

### ISSUE THREAD

**Issue by Dan-J-D** [rishi-raj-jain/astro-font#22]
When running astro in development mode, everything works as expected. However, when I build with node as my adapter and build it. It never loads the fonts.

This is in my `<head>`
```html
<AstroFont
	config={[
		{
			name: "BankPrinter",
			src: [
				{
					style: "inherit",
					weight: "inherit",
					path: "/fonts/BankPrinter.ttf",
				},
			],
			preload: true,
			fallback: "sans-serif",
			display: "swap",
			selector: ".BankPrinter",
		},
		{
			name: "StretchPro",
			src: [
				{
					style: "inherit",
					weight: "inherit",
					path: "/fonts/StretchPro.otf",
				},
			],
			preload: true,
			fallback: "sans-serif",
			display: "swap",
			selector: ".StretchPro",
		},
	]}
/>
```

In the `dist` folder
```html
<link href=/../../../../../../../..//fonts/BankPrinter.ttf rel=preload type=font/ttf as=font crossorigin>
<link href=/../../../../../../../..//fonts/StretchPro.otf rel=preload type=font/otf as=font crossorigin>
```

And if I change the paths to load paths like "./fonts/"..., it does this and still never loads the font.
```html
<link href=/../fonts/BankPrinter.ttf rel=preload type=font/ttf as=font crossorigin>
<link href=/../fonts/StretchPro.otf rel=preload type=font/otf as=font crossorigin>
```

Any fixes?

**Comment by rishi-raj-jain** [comment]
Hey @Dan-J-D,

In which directory in the project's directory do the font reside?

**Comment by Dan-J-D** [comment]
The fonts reside in astro's public directory with relative path of "./font/"...

Aswell, I have set preload to false and the fonts never get fetched. They have an inline css style but no request to fetch for the font

**Comment by rishi-raj-jain** [comment]
got it.

so you'd want to use this config instead:

```astro
---
import {join} from 'node:path';
import {AstroFont} from 'astro-font';
---

<AstroFont
	config={[
		{
			name: "BankPrinter",
			src: [
				{
					style: "inherit",
					weight: "inherit",
					path: join(process.cwd(), 'public', 'fonts', 'BankPrinter.ttf')
				},
			],
			preload: true,
			fallback: "sans-serif",
			display: "swap",
			selector: ".BankPrinter",
		},
		{
			name: "StretchPro",
			src: [
				{
					style: "inherit",
					weight: "inherit",
					path: join(process.cwd(), 'public', 'fonts', 'StretchPro.otf')
				},
			],
			preload: true,
			fallback: "sans-serif",
			display: "swap",
			selector: ".StretchPro",
		},
	]}
/>
```

**Comment by rishi-raj-jain** [comment]
> path of "./font/"...

or "./fonts/" instead? because I see that in your paths you are using /fonts and not /font

**Comment by Dan-J-D** [comment]
I have tried the above and it doesn't work. I believe it is because I am compiling with output mode as "hybrid" so the relative path there would be "../client/". Since, astro produces a `client` & `server` folder. But I have tried to fix this by setting the base path to "../client/" but after compiling it bugs out and produces this.

```html
<link href=/../web/fonts/BankPrinter.ttf rel=preload type=font/ttf as=font crossorigin>
<link href=/../../web/fonts/StretchPro.otf rel=preload type=font/otf as=font crossorigin>
```

**Comment by rishi-raj-jain** [comment]
oh nope, the paths won't changes as /client/ never comes into the play.

**Comment by rishi-raj-jain** [comment]
Can you share the project in a git repo or a zip?

I am happy to PR.

**Comment by Dan-J-D** [comment]
Yes, please give me a couple minutes to make a git repo.

**Comment by Dan-J-D** [comment]
Here you go: https://github.com/Dan-J-D/hello-world-font-test

**Comment by rishi-raj-jain** [comment]
Hey @Dan-J-D,

It works!

Here's how you'd wanna test it:

```bash
npm run build
npm run preview
```

I've created a PR.

**Comment by rishi-raj-jain** [comment]
https://github.com/rishi-raj-jain/astro-font/assets/46300090/401a5cdf-e944-45ab-842b-1cba5e35a009

**Comment by Dan-J-D** [comment]
@rishi-raj-jain Please try running in dev mode. The font should look like this

![image](https://github.com/rishi-raj-jain/astro-font/assets/52302961/2d85316a-9013-4748-b6c6-5f1f4c45f547)

**Comment by rishi-raj-jain** [comment]
Sure, checking out the dev mode.

**Comment by rishi-raj-jain** [comment]
Hey @Dan-J-D,

I just checked `astro-font` works just as fine.

The font files are messed up by `astro-critters`. Try removing the critters integration in my PR changes and you'd see the fonts would work as expected.

<img width="780" alt="Screenshot 2024-05-22 at 1 24 15 AM" src="https://github.com/rishi-raj-jain/astro-font/assets/46300090/d4db6c88-9d58-4a3c-b058-9bc5cf0f1ac1">

**Comment by Dan-J-D** [comment]
Oh, perfect. Thank you so much!

**Comment by rishi-raj-jain** [comment]
No worries!
