### ISSUE TITLE
Issue with Font Loading during View Transitions in Production Build

### ISSUE THREAD

**Issue by clover0916** [rishi-raj-jain/astro-font#27]
In development environment, fonts load correctly when using Astro <ViewTransitions /> for page navigation. However, in the production build, fonts do not display properly when navigating between pages.

Steps to reproduce:
1. Build the project for production
2. Navigate between pages using View Transitions
3. Observe that fonts are not rendering correctly

Expected behavior:
Fonts should load and display properly during View Transitions in both development and production environments.

Actual behavior:
Fonts render correctly in the development environment but fail to display properly in the production build when using View Transitions.

Note: This issue may be specific to my environment, but I wanted to report it in case others are experiencing similar problems.

Any assistance in resolving this font loading discrepancy between development and production environments would be greatly appreciated.

**Comment by clover0916** [comment]
I apologize for the confusion. Upon further investigation, I found that this issue was caused by a misconfiguration on my end, not a bug in astro-font. I'm closing this issue as it's no longer relevant. Thank you.

**Comment by rishi-raj-jain** [comment]
No worries, if there's anything that can be improved, do tell me!
