### ISSUE TITLE
Vercel Build will lead to a blank white page

### ISSUE THREAD

**Issue by FlipFloop** [rishi-raj-jain/astro-font#3]
Here is my code:

```
<html lang="en">
  <head>
    <Head title={title} description={description} />
    <AstroFont
      config={[
        {
          name: "Inter",
          src: [
            {
              style: "bold",
              weight: "300",
              path: "https://fonts.gstatic.com/s/inter/v13/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7W0Q5nw.woff2",
            },
          ],
          preload: true,
          display: "swap",
          selector: "body",
          fallback: "sans-serif",
        },
        {
          name: "Inter",
          src: [
            {
              style: "bold",
              weight: "700",
              path: "https://fonts.gstatic.com/s/inter/v13/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7W0Q5nw.woff2",
            },
          ],
          preload: true,
          display: "swap",
          selector: "body",
          fallback: "sans-serif",
        },
        {
          name: "IBM Plex Sans",
          src: [
            {
              style: "bold",
              weight: "400",
              path: "https://fonts.gstatic.com/s/ibmplexsans/v19/zYXgKVElMYYaJe8bpLHnCwDKhdHeFaxOedc.woff2",
            },
          ],
          preload: true,
          display: "swap",
          selector: "body",
          fallback: "sans-serif",
        },
      ]}
    />
  </head>
```

Here is my `package.json`

```  
"dependencies": {
    "@astrojs/mdx": "^2.0.2",
    "@astrojs/react": "^3.0.8",
    "@astrojs/sitemap": "^3.0.3",
    "@astrojs/vercel": "^6.1.0",
    "@mojs/core": "^1.7.1",
    "@mojs/player": "^1.3.0",
    "@react-three/drei": "^9.92.6",
    "@react-three/fiber": "^8.15.12",
    "@react-three/offscreen": "^0.0.8",
    "@react-three/postprocessing": "^2.15.11",
    "@types/react": "^18.2.45",
    "@types/react-dom": "^18.2.18",
    "@types/three": "^0.159.0",
    "astro": "^4.0.7",
    "astro-compress": "^2.2.5",
    "astro-font": "^0.0.28",
    "astro-icon": "^0.8.2",
    "astro-particles": "^2.10.0",
    "csv-parse": "^5.5.3",
    "highcharts": "^11.2.0",
    "lamina": "^1.1.23",
    "leaflet": "^1.9.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "three": "^0.159.0",
    "tsparticles": "^2.12.0",
    "tsparticles-engine": "^2.12.0"
  },
  "devDependencies": {
    "astro-robots-txt": "^1.0.0",
    "astro-seo": "^0.8.0",
    "autoprefixer": "^10.4.16",
    "cssnano": "^6.0.2",
    "prettier": "^3.1.1",
    "prettier-plugin-astro": "^0.12.2",
    "sass": "^1.69.5",
    "typescript": "^5.3.3"
  }
```

Here is the output: [https://victorguyard-loj2x1cca-victor-guyard-s-team.vercel.app/](https://victorguyard-loj2x1cca-victor-guyard-s-team.vercel.app/)
Original site (nothing different just added this package and tried to use it: [victorguyard.com](https://victorguyard.com).

No error logs in Vercel build or live logs.

**Comment by rishi-raj-jain** [comment]
Hey Yash,

Thanks for opening a detailed issue.

- Can you share a minimal reproduction of it? OR
- Is there a GitHub repo for [victorguyard.com](https://victorguyard.com/) where I can test and debug what's going wrong, and do a PR to get it working?

**Comment by pdkn** [comment]
This happens on Netlify too - any SSR hosting. The error is because when building on the server it's trying to make this folder at request time. I would suggest trying to add it to the package script at build time. As example 

```
"dev": "npm run generate-fonts && astro dev",
"build": "npm run generate-fonts && astro build"
```

This is current error that's resulting in a white page
```Dec 25, 05:43:22 PM: e860c6ac ERROR  Invoke Error 	{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, mkdir 'public/__astro_font_generated__'","code":"ENOENT","errno":-2,"syscall":"mkdir","path":"public/__astro_font_generated__","stack":["Error: ENOENT: no such file or directory, mkdir 'public/__astro_font_generated__'","    at Module.mkdirSync (node:fs:1398:3)","    at r2 (file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:2613:31)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async Promise.all (index 0)","    at async d3 (file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:2621:24)","    at async file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:8069:24","    at async AstroComponentInstance.render (file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:1357:11)","    at async Object.render (file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:1078:7)","    at async renderChild (file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:712:5)","    at async Object.renderToFinalDestination (file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:549:7)"]}Dec 25, 05:43:22 PM: e860c6ac ERROR  Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: ENOENT: no such file or directory, mkdir 'public/__astro_font_generated__'","reason":{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, mkdir 'public/__astro_font_generated__'","code":"ENOENT","errno":-2,"syscall":"mkdir","path":"public/__astro_font_generated__","stack":["Error: ENOENT: no such file or directory, mkdir 'public/__astro_font_generated__'","    at Module.mkdirSync (node:fs:1398:3)","    at r2 (file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:2613:31)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async Promise.all (index 0)","    at async d3 (file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:2621:24)","    at async file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:8069:24","    at async AstroComponentInstance.render (file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:1357:11)","    at async Object.render (file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:1078:7)","    at async renderChild (file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:712:5)","    at async Object.renderToFinalDestination (file:///var/task/.netlify/functions-internal/ssr/ssr.mjs:549:7)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: ENOENT: no such file or directory, mkdir 'public/__astro_font_generated__'","    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)","    at process.emit (node:events:517:28)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}```

**Comment by rishi-raj-jain** [comment]
@pdkn @FlipFloop Thank you for your patience 🙏🏻

I've just released a quick update to mitigate this while I figure out how to support both static and ssr modes with the cached result generated from the static/build mode/time.

> "dev": "npm run generate-fonts && astro dev",
> "build": "npm run generate-fonts && astro build"

Hmm, thinking...

**Comment by rishi-raj-jain** [comment]
@pdkn @FlipFloop

Is the issue still persistent with the latest fix I just rolled out?

**Comment by pdkn** [comment]
afraid it's still there. One of the issues is that after deploy the file system becomes read-only. `Error: EROFS: read-only file system, mkdir './public'"`. If someone is using fonts off google CDN it might be an idea to just load them from there rather than downloading to public folder. If people want to deploy fonts locally, they can manually download them off Google and follow that path. Consider allowing CDN loading of fonts?

**Comment by rishi-raj-jain** [comment]
@FlipFloop @pdkn 

Thank you both for your patience.

The latest published version now works correctly in all kind of writes.

Two major improvements:

- detect if buffer exists: https://github.com/rishi-raj-jain/astro-font/blob/master/packages/astro-font/utils.ts#L90-L92
- detect if writes can be done: https://github.com/rishi-raj-jain/astro-font/blob/master/packages/astro-font/utils.ts#L61-L70

Tested this working with a test deploy of SSRing the launchfa.st's homepage: https://launchfast-website-8a9sxuzn7-rishi-raj-jain.vercel.app/

**Comment by rishi-raj-jain** [comment]
Should work in all environments now.

Now, I'm trying to make sure how to support all platforms + configurations by looking into astro.config.mjs at the dev & build time.

**Comment by FlipFloop** [comment]
Thank you!

**Comment by rishi-raj-jain** [comment]
Okay so I've just released an update which makes it super compatible with all of the configurations, taking care of `notFetch`.

One can use `fetch` attribute instead in case they want the lib to download and place the font on their projects.

**Comment by rishi-raj-jain** [comment]
> If someone is using fonts off google CDN it might be an idea to just load them from there rather than downloading to public folder. If people want to deploy fonts locally, they can manually download them off Google and follow that path. Consider allowing CDN loading of fonts?

Sure thing! The latest release shall have this by default now.

**Comment by FlipFloop** [comment]
Do we have to change anything then?
From the original:

```
<AstroFont
  config={[
    {
      name: "Inter",
      src: [
        {
          style: "bold",
          weight: "300",
          path: "https://fonts.gstatic.com/s/inter/v13/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7W0Q5nw.woff2",
        },
        {
          style: "bold",
          weight: "700",
          path: "https://fonts.gstatic.com/s/inter/v13/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7W0Q5nw.woff2",
        },
      ],
      preload: true,
      display: "swap",
      selector: "body",
      fallback: "sans-serif",
    },
    {
      name: "IBM Plex Sans",
      src: [
        {
          style: "bold",
          weight: "400",
          path: "https://fonts.gstatic.com/s/ibmplexsans/v19/zYXgKVElMYYaJe8bpLHnCwDKhdHeFaxOedc.woff2",
        },
      ],
      preload: true,
      display: "swap",
      selector: "body",
      fallback: "sans-serif",
    },
  ]}
/>
```

**Comment by rishi-raj-jain** [comment]
Yup, this looks cool! You might want to take care of duplicate `selector: "body"` for different fonts.
