### ISSUE TITLE
Error `no such file or directory` trying to load the .txt file from temp

### ISSUE THREAD

**Issue by khoait** [rishi-raj-jain/astro-font#5]
Hi,

I'm using `"astro-font": "^0.0.60"`  and having this error when run build.

![image](https://github.com/rishi-raj-jain/astro-font/assets/8686497/aa726dcc-47e7-46ca-9044-9381452eefc7)

**Comment by rishi-raj-jain** [comment]
@khoait 

Thanks for reporting! Looking into this...

**Comment by rishi-raj-jain** [comment]
@khoait 

Can you share your `AstroFont` configuration?

https://github.com/rishi-raj-jain/astro-font/blob/master/packages/astro-font/utils.ts#L186-L190 shall only load it when it's present 👀

**Comment by khoait** [comment]
Hi @rishi-raj-jain 

my `AstroFont` config:

```Astro
---
import { AstroFont } from "astro-font";
---

<AstroFont
  config={[
    {
      name: "Inter",
      src: [
        {
          style: "normal",
          weight: "400",
          path: "https://fonts.gstatic.com/s/inter/v13/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2pL7SUc.woff2",
        },
        {
          style: "normal",
          weight: "500",
          path: "https://fonts.gstatic.com/s/inter/v13/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2pL7SUc.woff2",
        },
        {
          style: "normal",
          weight: "700",
          path: "https://fonts.gstatic.com/s/inter/v13/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2pL7SUc.woff2",
        },
      ],
      preload: true,
      display: "swap",
      selector: "body",
      fallback: "sans-serif",
    },
  ]}
/>
```

**Comment by rishi-raj-jain** [comment]
@khoait 

Thanks for sharing the config!

It helped me:

- fix the [long filename](https://github.com/rishi-raj-jain/astro-font/blob/master/packages/astro-font/utils.ts#L117-L126) problem that occured while reproducing the issue
- write idiomatic code to scope operations that are not vital and implement error handling: https://github.com/rishi-raj-jain/astro-font/blob/master/packages/astro-font/utils.ts#L201-L207

**Comment by rishi-raj-jain** [comment]
Can you upgrade via:

```bash
pnpm add astro-font@latest
```

Also, by default the files are NOT created and localized.

To make sure the files are fetched and read from the local, add the `fetch` flag to your config object.

<img width="297" alt="Screenshot 2024-01-08 at 11 49 21 AM" src="https://github.com/rishi-raj-jain/astro-font/assets/46300090/1b98478d-a851-4f80-9ba0-1f50a63facb2">

**Comment by khoait** [comment]
Hi @rishi-raj-jain, thanks for your quick response!

the error seems to be resolved and I can see local files are created correctly.

now I encounter another error. I'm using `"astro-i18n": "^2.2.0"` and there are some conflicts with astro-font I think.

![image](https://github.com/rishi-raj-jain/astro-font/assets/8686497/7d3d17ab-273a-45aa-8b4f-80f0df612e14)

**Stacktrace**
```
TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at set route [as route] (C:\Users\------\node_modules\astro-i18n\dist\src\index.js:12:30049)
    at C:\Users\------\node_modules\astro-i18n\dist\src\index.js:12:36645
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/------/node_modules/astro/dist/i18n/middleware.js:35:22
    at async callMiddleware (file:///C:/Users/------/node_modules/astro/dist/core/middleware/callMiddleware.js:12:10)
    at async #tryRenderRoute (file:///C:/------/node_modules/astro/dist/core/pipeline.js:101:18)
    at async DevPipeline.renderRoute (file:///C:/Users/------/node_modules/astro/dist/core/pipeline.js:58:20)
    at async handleRoute (file:///C:/Users/------/node_modules/astro/dist/vite-plugin-astro-server/route.js:248:18)
    at async run (file:///C:/Users/------/astro/dist/vite-plugin-astro-server/request.js:50:14)
    at async runWithErrorHandling (file:///C:/Users/------/node_modules/astro/dist/vite-plugin-astro-server/controller.js:64:5)
    at async handleRequest (file:///C:/Users/------/node_modules/astro/dist/vite-plugin-astro-server/request.js:44:3)
```

Maybe this can go to another issue. Unfortunately I'll have to remove `astro-font` for now and use google font links instead.

**Comment by rishi-raj-jain** [comment]
@khoait 

Thank you for getting back to me!

Per the error log, I do not think this is related `astro-font`.

- Do let me know if after removing `astro-font` it works fine
- Feel free to drop a GH link to the repo if possible so that I can spend my time into crafting the perfect experience of `astro-font`

**Comment by khoait** [comment]
@rishi-raj-jain yes, removing `astro-font` it works ok. you can see the error in this branch https://github.com/khoait/3edesign/tree/astro-font

**Comment by rishi-raj-jain** [comment]
@khoait 

Hey, I just tested and it did build fine. The steps I followed:

- git clone https://github.com/khoait/3edesign/tree/astro-font
- npm install
- npm install astro-font@latest
- npm run build

**Comment by rishi-raj-jain** [comment]
Uploading Screen Recording 2024-01-08 at 6.28.19 PM.mp4…

**Comment by rishi-raj-jain** [comment]
https://github.com/rishi-raj-jain/astro-font/assets/46300090/a469948c-9cf9-4996-b317-0b4864d2f7bb

**Comment by rishi-raj-jain** [comment]
Totally appreciate your feedback and time that you took! Hope you get the time to try this again soon...

**Comment by khoait** [comment]
ok, that's strange. I see the error when running `npm run dev`. build then preview is ok though 😕

**Comment by khoait** [comment]
https://github.com/rishi-raj-jain/astro-font/assets/8686497/35b19224-6774-4cb9-bac7-cb3243f99e40

**Comment by rishi-raj-jain** [comment]
Hey @khoait,

Thank you for taking the time.

Even after you remove the `astro-font` lib, it errors out as the error is within the dev mode while using `astro-i18n`.

Please have a look:

https://github.com/rishi-raj-jain/astro-font/assets/46300090/8ce16f5f-74bc-4c31-852e-530927cdbd89

**Comment by rishi-raj-jain** [comment]
Even in the error logs of the screen recording you sent, the error is pointing out to: `astro-i18n`

<img width="673" alt="Screenshot 2024-01-08 at 9 37 12 PM" src="https://github.com/rishi-raj-jain/astro-font/assets/46300090/d3a5fc31-edff-4a94-b0f4-95f8a7fda7e2">

**Comment by khoait** [comment]
Yeah, i can see it. That's why i mentioned there is some conflicts with `astro-i18n` only when `astro-font` is installed.
Anyway i really apprecitate your support! I'll look into this later when my project is more stable.

**Comment by rishi-raj-jain** [comment]
> only when astro-font is installed.

Uninstalled it 👇🏻

https://github.com/rishi-raj-jain/astro-font/assets/46300090/a07fb9f4-0bc9-48cd-94e8-6d5497ec37aa

**Comment by rishi-raj-jain** [comment]
> Anyway i really apprecitate your support!

My pleasure 🤞🏻

**Comment by rishi-raj-jain** [comment]
> I'll look into this later when my project is more stable.

Alright
