### ISSUE TITLE
Not working with local fonts.

### ISSUE THREAD

**Issue by ulysses-ck** [rishi-raj-jain/astro-font#7]
I'm using astro latest version 4.1.2 and astro-font 0.0.72.
My operative system is Windows 10.
The browser is Chrome.

The problem is that I'm trying to load a local font and I don't know, but the url resolved is bad and report obviously a 404.
![image](https://github.com/rishi-raj-jain/astro-font/assets/50756389/cc73959e-5da0-48ad-bff4-b82ecae3285c)  
Also, I'm using the same code that rely the example in your repository:
```
<AstroFont
      config={[
        {
          name: "Afacad",
          src: [
            {
              style: "normal",
              weight: "400",
              path: "./public/fonts/Afacad-Regular.woff2",
            },
            {
              style: "medium",
              weight: "500",
              path: "./public/fonts/Afacad-Medium.woff2",
            },
          ],
          preload: false,
          display: "swap",
          selector: "body",
          fallback: "sans-serif",
        },
      ]}
    />
```
And the same structure file.
![image](https://github.com/rishi-raj-jain/astro-font/assets/50756389/81f44d0b-aca1-47a4-833d-51bdbf291d3d)
The URL resolved:
![image](https://github.com/rishi-raj-jain/astro-font/assets/50756389/b2ec6c8c-2e0c-4a6d-a02c-fcdf655079d6)

**Comment by rishi-raj-jain** [comment]
Hey @ulysses-ck,

Actually, you need to use node specific delimiters. 

https://github.com/rishi-raj-jain/astro-font?tab=readme-ov-file#local-fonts is how you can do it.

**Comment by ulysses-ck** [comment]
Thanks, it is working right now in production.
![image](https://github.com/rishi-raj-jain/astro-font/assets/50756389/fcbebd68-3671-4ac1-8928-560cfb51bd9b)

I don't know why doesn't work in development mode. But thanks. I suspect is the problem of windows with the subject of the backslash

**Comment by rishi-raj-jain** [comment]
> you need to use node specific delimiters.
> 
> https://github.com/rishi-raj-jain/astro-font?tab=readme-ov-file#local-fonts is how you can do it.

Yeah, with node specific delimiters it would even work in development mode as well.

https://github.com/rishi-raj-jain/astro-font?tab=readme-ov-file#local-fonts is how you can do it.

**Comment by rishi-raj-jain** [comment]
@kingpr0o7 had the same issue and using join solved it. Hence, I've updated the docs to reflect the correct usage everywhere.

**Comment by rishi-raj-jain** [comment]
https://github.com/KingPr0o7/portfolio/blob/main/src/layouts/Layout.astro#L119-L142 is the current way how it works well in Windows. Basically, what we see here: https://github.com/rishi-raj-jain/astro-font?tab=readme-ov-file#local-fonts.

**Comment by Azuronate** [comment]
Can confirm this works!

**Comment by rishi-raj-jain** [comment]
Thank you, @KingPr0o7!
