### ISSUE TITLE
font request: geist & geist mono

### ISSUE THREAD

**Issue by thatgurkangurk** [rishi-raj-jain/astro-font#8]
it would be great if the library natively had the [geist/geist mono font](https://vercel.com/font) _as it is my favourite font_

I could make a pr for it if you’d like just let me know :)

**Comment by thatgurkangurk** [comment]
this would only work if the library has bundled fonts, if it just uses google fonts url behind the scenes then it would be less useful I suppose

**Comment by rishi-raj-jain** [comment]
Hey @thatgurkangurk,

Thank you for proposing! I'll definitely look into updating the package to support fonts.

I do see the value of it as `@fontsource` installs seems to be bonkers as they help you load font files as dependency with Vite, but not sure if it's worth the effort if I can already optimize **even** over the network using `astro-font`.
