### ISSUE TITLE
Path are malformed

### ISSUE THREAD

**Issue by florian-lefebvre** [rishi-raj-jain/astro-font#9]
When using local fonts, path are malformed. For example, doing:
```jsx
<AstroFont
  config={[
    {
      name: "Deacon Black",
      src: [
        {
          style: "normal",
          weight: 900,
          path: join(
            process.cwd(),
            "public",
            "assets",
            "fonts",
            "Deacon-Black.woff2"
          ),
        },
      ],
      preload: true,
      display: "swap",
      fallback: "sans-serif",
      cssVariable: "deacon-black-font",
    },
  ]}
/>
```
will output the following path in both style and meta tags: `/assets\fonts\Deacon-Black.woff2`.

If that can help, I'm on windows

**Comment by rishi-raj-jain** [comment]
Hey @florian-lefebvre,

Is that the dev mode you're seeing that in?

**Comment by florian-lefebvre** [comment]
Yep

**Comment by rishi-raj-jain** [comment]
Does that same happen after build & preview step?

**Comment by florian-lefebvre** [comment]
I don't know but it completely breaks the package in dev mode, which is unfortunate. I think what you can do is either:
- Replace any `\` by `/`
- Use https://github.com/unjs/pathe

**Comment by rishi-raj-jain** [comment]
@florian-lefebvre 

Done! Please try with the latest?

**Comment by rishi-raj-jain** [comment]
> Use https://github.com/unjs/pathe

This is amazing!

**Comment by rishi-raj-jain** [comment]
> Use https://github.com/unjs/pathe

This is amazing! cc @pi0

**Comment by florian-lefebvre** [comment]
That works thanks!
